localgov_login_redirect.settings:
  type: config_object
  label: 'LocalGov Login Redirect settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    redirect_route:
      type: string
      label: 'Redirection route'
